name: mart_connect
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  firebase_core:
  firebase_auth:
  cloud_firestore:
  fluttertoast: ^8.2.4
  uuid:
  flutter_launcher_icons: ^0.13.1
  firebase_storage:
  image_picker: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.11

  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  custom_marker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/


